In [1]:
import numpy as np

In [2]:
def matrix_size():
    check= True
    while check:
        dim= int(input('Enter N: '))
        if dim > 3:
            check= False
            continue
        print ('N must be more than 3')
        
    return dim

In [3]:
dim= matrix_size()

Enter N: 5


In [4]:
def N_queen_matrix(dim):
    return np.zeros(shape= (dim, dim), dtype= int)

In [5]:
N_queen_mat= N_queen_matrix(dim)

In [6]:
def is_safe(N_queen_mat, row, col):
    
    # از مقدار سطر و ستونی که به عنوان پارامتر فرستاده ایم ، تا اولین ستون از آن سطر بررسی میکنیم، در صورتی که  مقادیر یکی از آن 
    #ستونها یک بود مقدار فالس را برگردان
    # این بدان منظور هست که در یک سطر دو وزیر قرار ندهیم 
    #ما بررسی را از سطر و ستون  پارامتر "رو، کال" شروع میکنیم تا به ستون اولی برسیم. این کار باعث میشود که تعداد بررسی ها کم شده
    #و سرعت اجرای بالاتری داشته باشیم  
    for j in range(col, -1, -1):
        if N_queen_mat[row, j] == 1:
            return False
        
     #از مقدار پارامتر هایی که به عنوان سطر و ستون فرستاده شده شروع میکنیم و از ان نقطه رو به بالا به صورت مورب بررسی میکنیم
    #درصورتی که وزیری در مسیر بررسی وجود داشت ، مقدار فالس را بر میگرداند
    #حالت بهینه کردن قبلی را نیز لحاظ میکنیم. تا بررسی کمتری انجام شود    
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if N_queen_mat[i, j] == 1:
            return False
    
    #از مقدار پارامتر هایی که به عنوان سطر و ستون فرستاده شده شروع میکنیم و از ان نقطه رو به پایین به صورت مورب بررسی میکنیم
    #درصورتی که وزیری در مسیر بررسی وجود داشت ، مقدار فالس را بر میگرداند
    #حالت بهینه کردن قبلی را نیز لحاظ میکنیم. تا بررسی کمتری انجام شود   
    for i, j in zip(range(row,len(N_queen_mat),1), range(col,-1,-1)):
        if N_queen_mat[i,j] == 1:
            return False
        
    return True

In [7]:
def fill(N_queen_mat, j, check, specific_row= 0):
    c= 0
    for i in range(specific_row, len(N_queen_mat)):
        if is_safe(N_queen_mat, i, j):
            N_queen_mat[i, j]= 1
#             check= 0
            c= 1
            break
    if c is 0:
        check= 1
    else:
        check= 0
    return N_queen_mat, check
            

In [8]:
def fill_final(N_queen_mat):
    col= len(N_queen_mat)
    row= len(N_queen_mat)
    check= 0
    j= 0
    while True:
        if check is 0:
            N_queen_mat, check= fill(N_queen_mat, j, check)

        if check is 1 :
            j= j - 1
            print('j is: ', j)
            find_one_row_index= np.where(N_queen_mat[:, j])[0][0]
            print(find_one_row_index)
            if find_one_row_index < len(N_queen_mat)-1:
                N_queen_mat[find_one_row_index, j]= 0
                
                N_queen_mat, check= fill(N_queen_mat, j, check, find_one_row_index + 1)
                if check is 1:
                    j= j - 1
            elif find_one_row_index == len(N_queen_mat)- 1:
                print('\nthis\n')
                N_queen_mat[find_one_row_index, j]= 0
                j-= 1
                find_one_row_index= np.where(N_queen_mat[:, j])[0][0]
                N_queen_mat[find_one_row_index, j]= 0
                
                N_queen_mat, check= fill(N_queen_mat, j, check, find_one_row_index + 1)
                if check is 1:
                    j = j - 1
        print(N_queen_mat)
        print('\n -------------------------------\n')
        j+= 1
        if j >= len(N_queen_mat):
            break
    return N_queen_mat              
            

In [9]:
fill_final(N_queen_mat)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

 -------------------------------

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

 -------------------------------

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]

 -------------------------------

[[1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]

 -------------------------------

[[1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]

 -------------------------------



array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0]])